# 1. CRIAÇÃO DO VOLUME (Onde os dados serão salvos)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-api-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 2. DEPLOYMENT DO APP (O "Corpo" da aplicação)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  labels:
    app: simple-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api
        image: alexandrephilippusneto/simple-api:latest
        ports:
        - containerPort: 5687

        # Montagem do volume dentro do container
        volumeMounts:
        - name: storage-volume
          mountPath: /app/data

        # Configurações de Recursos (Evita o "Noisy Neighbor")
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

        # Verificações de Saúde (Probes)
        livenessProbe:
          httpGet:
            path: /health
            port: 5687
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5687
          initialDelaySeconds: 10
          periodSeconds: 5

      # Vinculação do container com o PVC criado acima
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: simple-api-pvc
---
# 3. SERVICE NODEPORT (Acesso via navegador/externo)
apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
spec:
  type: NodePort
  selector:
    app: simple-api
  ports:
    - protocol: TCP
      port: 5687        # Porta interna do Service
      targetPort: 5687   # Porta do seu App (container)
      nodePort: 30001    # Porta que você vai abrir no seu IP/Localhost